export const countries = [
  { code: "AF", cuisine: "Afghan" },
  { code: "AL", cuisine: "Albanian" },
  { code: "DZ", cuisine: "Algerian" },
  { code: "AD", cuisine: "Andorran" },
  { code: "AO", cuisine: "Angolan" },
  { code: "AG", cuisine: "Antiguan and Barbudan" },
  { code: "AR", cuisine: "Argentinian" },
  { code: "AM", cuisine: "Armenian" },
  { code: "AU", cuisine: "Australian" },
  { code: "AT", cuisine: "Austrian" },
  { code: "AZ", cuisine: "Azerbaijani" },
  { code: "BS", cuisine: "Bahamian" },
  { code: "BH", cuisine: "Bahraini" },
  { code: "BD", cuisine: "Bangladeshi" },
  { code: "BB", cuisine: "Barbadian" },
  { code: "BY", cuisine: "Belarusian" },
  { code: "BE", cuisine: "Belgian" },
  { code: "BZ", cuisine: "Belizean" },
  { code: "BJ", cuisine: "Beninese" },
  { code: "BT", cuisine: "Bhutanese" },
  { code: "BO", cuisine: "Bolivian" },
  { code: "BA", cuisine: "Bosnian" },
  { code: "BR", cuisine: "Brazilian" },
  { code: "BN", cuisine: "Bruneian" },
  { code: "BG", cuisine: "Bulgarian" },
  { code: "BF", cuisine: "Burkinabe" },
  { code: "BI", cuisine: "Burundian" },
  { code: "KH", cuisine: "Cambodian" },
  { code: "CM", cuisine: "Cameroonian" },
  { code: "CA", cuisine: "Canadian" },
  { code: "CV", cuisine: "Cape Verdean" },
  { code: "CF", cuisine: "Central African" },
  { code: "TD", cuisine: "Chadian" },
  { code: "CL", cuisine: "Chilean" },
  { code: "CN", cuisine: "Chinese" },
  { code: "CO", cuisine: "Colombian" },
  { code: "KM", cuisine: "Comoran" },
  { code: "CG", cuisine: "Congolese" },
  { code: "CR", cuisine: "Costa Rican" },
  { code: "HR", cuisine: "Croatian" },
  { code: "CU", cuisine: "Cuban" },
  { code: "CY", cuisine: "Cypriot" },
  { code: "CZ", cuisine: "Czech" },
  { code: "DK", cuisine: "Danish" },
  { code: "DJ", cuisine: "Djiboutian" },
  { code: "DM", cuisine: "Dominican" },
  { code: "DO", cuisine: "Dominican" },
  { code: "EC", cuisine: "Ecuadorian" },
  { code: "EG", cuisine: "Egyptian" },
  { code: "SV", cuisine: "Salvadoran" },
  { code: "GQ", cuisine: "Equatorial Guinean" },
  { code: "ER", cuisine: "Eritrean" },
  { code: "EE", cuisine: "Estonian" },
  { code: "ET", cuisine: "Ethiopian" },
  { code: "FJ", cuisine: "Fijian" },
  { code: "FI", cuisine: "Finnish" },
  { code: "FR", cuisine: "French" },
  { code: "GA", cuisine: "Gabonese" },
  { code: "GM", cuisine: "Gambian" },
  { code: "GE", cuisine: "Georgian" },
  { code: "DE", cuisine: "German" },
  { code: "GH", cuisine: "Ghanaian" },
  { code: "GR", cuisine: "Greek" },
  { code: "GD", cuisine: "Grenadian" },
  { code: "GT", cuisine: "Guatemalan" },
  { code: "GN", cuisine: "Guinean" },
  { code: "GW", cuisine: "Guinea-Bissauan" },
  { code: "GY", cuisine: "Guyanese" },
  { code: "HT", cuisine: "Haitian" },
  { code: "HN", cuisine: "Honduran" },
  { code: "HU", cuisine: "Hungarian" },
  { code: "IS", cuisine: "Icelandic" },
  { code: "IN", cuisine: "Indian" },
  { code: "ID", cuisine: "Indonesian" },
  { code: "IR", cuisine: "Iranian" },
  { code: "IQ", cuisine: "Iraqi" },
  { code: "IE", cuisine: "Irish" },
  { code: "IL", cuisine: "Israeli" },
  { code: "IT", cuisine: "Italian" },
  { code: "JM", cuisine: "Jamaican" },
  { code: "JP", cuisine: "Japanese" },
  { code: "JO", cuisine: "Jordanian" },
  { code: "KZ", cuisine: "Kazakhstani" },
  { code: "KE", cuisine: "Kenyan" },
  { code: "KI", cuisine: "Kiribatian" },
  { code: "KW", cuisine: "Kuwaiti" },
  { code: "KG", cuisine: "Kyrgyz" },
  { code: "LA", cuisine: "Laotian" },
  { code: "LV", cuisine: "Latvian" },
  { code: "LB", cuisine: "Lebanese" },
  { code: "LS", cuisine: "Lesotho" },
  { code: "LR", cuisine: "Liberian" },
  { code: "LY", cuisine: "Libyan" },
  { code: "LI", cuisine: "Liechtensteiner" },
  { code: "LT", cuisine: "Lithuanian" },
  { code: "LU", cuisine: "Luxembourgish" },
  { code: "MG", cuisine: "Malagasy" },
  { code: "MW", cuisine: "Malawian" },
  { code: "MY", cuisine: "Malaysian" },
  { code: "MV", cuisine: "Maldivian" },
  { code: "ML", cuisine: "Malian" },
  { code: "MT", cuisine: "Maltese" },
  { code: "MH", cuisine: "Marshallese" },
  { code: "MR", cuisine: "Mauritanian" },
  { code: "MU", cuisine: "Mauritian" },
  { code: "MX", cuisine: "Mexican" },
  { code: "FM", cuisine: "Micronesian" },
  { code: "MD", cuisine: "Moldovan" },
  { code: "MC", cuisine: "Monacan" },
  { code: "MN", cuisine: "Mongolian" },
  { code: "ME", cuisine: "Montenegrin" },
  { code: "MA", cuisine: "Moroccan" },
  { code: "MZ", cuisine: "Mozambican" },
  { code: "MM", cuisine: "Myanmar" },
  { code: "NA", cuisine: "Namibian" },
  { code: "NR", cuisine: "Nauruan" },
  { code: "NP", cuisine: "Nepalese" },
  { code: "NL", cuisine: "Dutch" },
  { code: "NZ", cuisine: "New Zealand" },
  { code: "NI", cuisine: "Nicaraguan" },
  { code: "NE", cuisine: "Nigerien" },
  { code: "NG", cuisine: "Nigerian" },
  { code: "KP", cuisine: "North Korean" },
  { code: "MK", cuisine: "North Macedonian" },
  { code: "NO", cuisine: "Norwegian" },
  { code: "OM", cuisine: "Omani" },
  { code: "PK", cuisine: "Pakistani" },
  { code: "PW", cuisine: "Palauan" },
  { code: "PA", cuisine: "Panamanian" },
  { code: "PG", cuisine: "Papua New Guinean" },
  { code: "PY", cuisine: "Paraguayan" },
  { code: "PE", cuisine: "Peruvian" },
  { code: "PH", cuisine: "Filipino" },
  { code: "PL", cuisine: "Polish" },
  { code: "PT", cuisine: "Portuguese" },
  { code: "QA", cuisine: "Qatari" },
  { code: "RO", cuisine: "Romanian" },
  { code: "RU", cuisine: "Russian" },
  { code: "RW", cuisine: "Rwandan" },
  { code: "KN", cuisine: "Saint Kitts and Nevis" },
  { code: "LC", cuisine: "Saint Lucian" },
  { code: "VC", cuisine: "Saint Vincent and the Grenadines" },
  { code: "WS", cuisine: "Samoan" },
  { code: "SM", cuisine: "San Marinese" },
  { code: "ST", cuisine: "Sao Tomean" },
  { code: "SA", cuisine: "Saudi Arabian" },
  { code: "SN", cuisine: "Senegalese" },
  { code: "RS", cuisine: "Serbian" },
  { code: "SC", cuisine: "Seychellois" },
  { code: "SL", cuisine: "Sierra Leonean" },
  { code: "SG", cuisine: "Singaporean" },
  { code: "SK", cuisine: "Slovak" },
  { code: "SI", cuisine: "Slovenian" },
  { code: "SB", cuisine: "Solomon Islander" },
  { code: "SO", cuisine: "Somali" },
  { code: "ZA", cuisine: "South African" },
  { code: "KR", cuisine: "South Korean" },
  { code: "SS", cuisine: "South Sudanese" },
  { code: "ES", cuisine: "Spanish" },
  { code: "LK", cuisine: "Sri Lankan" },
  { code: "SD", cuisine: "Sudanese" },
  { code: "SR", cuisine: "Surinamese" },
  { code: "SZ", cuisine: "Swazi" },
  { code: "SE", cuisine: "Swedish" },
  { code: "CH", cuisine: "Swiss" },
  { code: "SY", cuisine: "Syrian" },
  { code: "TJ", cuisine: "Tajik" },
  { code: "TZ", cuisine: "Tanzanian" },
  { code: "TH", cuisine: "Thai" },
  { code: "TL", cuisine: "Timorese" },
  { code: "TG", cuisine: "Togolese" },
  { code: "TO", cuisine: "Tongan" },
  { code: "TT", cuisine: "Trinidadian or Tobagonian" },
  { code: "TN", cuisine: "Tunisian" },
  { code: "TR", cuisine: "Turkish" },
  { code: "TM", cuisine: "Turkmen" },
  { code: "TV", cuisine: "Tuvaluan" },
  { code: "UG", cuisine: "Ugandan" },
  { code: "UA", cuisine: "Ukrainian" },
  { code: "AE", cuisine: "Emirati" },
  { code: "GB", cuisine: "British" },
  { code: "US", cuisine: "American" },
  { code: "UY", cuisine: "Uruguayan" },
  { code: "UZ", cuisine: "Uzbekistani" },
  { code: "VU", cuisine: "Vanuatuan" },
  { code: "VA", cuisine: "Vatican" },
  { code: "VE", cuisine: "Venezuelan" },
  { code: "VN", cuisine: "Vietnamese" },
  { code: "YE", cuisine: "Yemeni" },
  { code: "ZM", cuisine: "Zambian" },
  { code: "ZW", cuisine: "Zimbabwean" },
];
