export const cuisines = [
  { code: "af", name: "Afghan" },
  { code: "al", name: "Albanian" },
  { code: "dz", name: "Algerian" },
  { code: "ad", name: "Andorran" },
  { code: "ao", name: "Angolan" },
  { code: "ag", name: "Antiguan and Barbudan" },
  { code: "ar", name: "Argentinian" },
  { code: "am", name: "Armenian" },
  { code: "au", name: "Australian" },
  { code: "at", name: "Austrian" },
  { code: "az", name: "Azerbaijani" },
  { code: "bs", name: "Bahamian" },
  { code: "bh", name: "Bahraini" },
  { code: "bd", name: "Bangladeshi" },
  { code: "bb", name: "Barbadian" },
  { code: "by", name: "Belarusian" },
  { code: "be", name: "Belgian" },
  { code: "bz", name: "Belizean" },
  { code: "bj", name: "Beninese" },
  { code: "bt", name: "Bhutanese" },
  { code: "bo", name: "Bolivian" },
  { code: "ba", name: "Bosnian" },
  { code: "br", name: "Brazilian" },
  { code: "bn", name: "Bruneian" },
  { code: "bg", name: "Bulgarian" },
  { code: "bf", name: "Burkinabe" },
  { code: "bi", name: "Burundian" },
  { code: "kh", name: "Cambodian" },
  { code: "cm", name: "Cameroonian" },
  { code: "ca", name: "Canadian" },
  { code: "cv", name: "Cape Verdean" },
  { code: "cf", name: "Central African" },
  { code: "td", name: "Chadian" },
  { code: "cl", name: "Chilean" },
  { code: "cn", name: "Chinese" },
  { code: "co", name: "Colombian" },
  { code: "km", name: "Comoran" },
  { code: "cg", name: "Congolese" },
  { code: "cr", name: "Costa Rican" },
  { code: "hr", name: "Croatian" },
  { code: "cu", name: "Cuban" },
  { code: "cy", name: "Cypriot" },
  { code: "cz", name: "Czech" },
  { code: "dk", name: "Danish" },
  { code: "dj", name: "Djiboutian" },
  { code: "dm", name: "Dominican" },
  { code: "do", name: "Dominican" },
  { code: "ec", name: "Ecuadorian" },
  { code: "eg", name: "Egyptian" },
  { code: "sv", name: "Salvadoran" },
  { code: "gq", name: "Equatorial Guinean" },
  { code: "er", name: "Eritrean" },
  { code: "ee", name: "Estonian" },
  { code: "et", name: "Ethiopian" },
  { code: "fj", name: "Fijian" },
  { code: "fi", name: "Finnish" },
  { code: "fr", name: "French" },
  { code: "ga", name: "Gabonese" },
  { code: "gm", name: "Gambian" },
  { code: "ge", name: "Georgian" },
  { code: "de", name: "German" },
  { code: "gh", name: "Ghanaian" },
  { code: "gr", name: "Greek" },
  { code: "gd", name: "Grenadian" },
  { code: "gt", name: "Guatemalan" },
  { code: "gn", name: "Guinean" },
  { code: "gw", name: "Guinea-Bissauan" },
  { code: "gy", name: "Guyanese" },
  { code: "ht", name: "Haitian" },
  { code: "hn", name: "Honduran" },
  { code: "hu", name: "Hungarian" },
  { code: "is", name: "Icelandic" },
  { code: "in", name: "Indian" },
  { code: "id", name: "Indonesian" },
  { code: "ir", name: "Iranian" },
  { code: "iq", name: "Iraqi" },
  { code: "ie", name: "Irish" },
  { code: "il", name: "Israeli" },
  { code: "it", name: "Italian" },
  { code: "jm", name: "Jamaican" },
  { code: "jp", name: "Japanese" },
  { code: "jo", name: "Jordanian" },
  { code: "kz", name: "Kazakhstani" },
  { code: "ke", name: "Kenyan" },
  { code: "ki", name: "Kiribatian" },
  { code: "kw", name: "Kuwaiti" },
  { code: "kg", name: "Kyrgyz" },
  { code: "la", name: "Laotian" },
  { code: "lv", name: "Latvian" },
  { code: "lb", name: "Lebanese" },
  { code: "ls", name: "Lesotho" },
  { code: "lr", name: "Liberian" },
  { code: "ly", name: "Libyan" },
  { code: "li", name: "Liechtensteiner" },
  { code: "lt", name: "Lithuanian" },
  { code: "lu", name: "Luxembourgish" },
  { code: "mg", name: "Malagasy" },
  { code: "mw", name: "Malawian" },
  { code: "my", name: "Malaysian" },
  { code: "mv", name: "Maldivian" },
  { code: "ml", name: "Malian" },
  { code: "mt", name: "Maltese" },
  { code: "mh", name: "Marshallese" },
  { code: "mr", name: "Mauritanian" },
  { code: "mu", name: "Mauritian" },
  { code: "mx", name: "Mexican" },
  { code: "fm", name: "Micronesian" },
  { code: "md", name: "Moldovan" },
  { code: "mc", name: "Monacan" },
  { code: "mn", name: "Mongolian" },
  { code: "me", name: "Montenegrin" },
  { code: "ma", name: "Moroccan" },
  { code: "mz", name: "Mozambican" },
  { code: "mm", name: "Myanmar" },
  { code: "na", name: "Namibian" },
  { code: "nr", name: "Nauruan" },
  { code: "np", name: "Nepalese" },
  { code: "nl", name: "Dutch" },
  { code: "nz", name: "New Zealand" },
  { code: "ni", name: "Nicaraguan" },
  { code: "ne", name: "Nigerien" },
  { code: "ng", name: "Nigerian" },
  { code: "kp", name: "North Korean" },
  { code: "mk", name: "North Macedonian" },
  { code: "no", name: "Norwegian" },
  { code: "om", name: "Omani" },
  { code: "pk", name: "Pakistani" },
  { code: "pw", name: "Palauan" },
  { code: "pa", name: "Panamanian" },
  { code: "pg", name: "Papua New Guinean" },
  { code: "py", name: "Paraguayan" },
  { code: "pe", name: "Peruvian" },
  { code: "ph", name: "Filipino" },
  { code: "pl", name: "Polish" },
  { code: "pt", name: "Portuguese" },
  { code: "qa", name: "Qatari" },
  { code: "ro", name: "Romanian" },
  { code: "ru", name: "Russian" },
  { code: "rw", name: "Rwandan" },
  { code: "kn", name: "Saint Kitts and Nevis" },
  { code: "lc", name: "Saint Lucian" },
  { code: "vc", name: "Saint Vincent and the Grenadines" },
  { code: "ws", name: "Samoan" },
  { code: "sm", name: "San Marinese" },
  { code: "st", name: "Sao Tomean" },
  { code: "sa", name: "Saudi Arabian" },
  { code: "sn", name: "Senegalese" },
  { code: "rs", name: "Serbian" },
  { code: "sc", name: "Seychellois" },
  { code: "sl", name: "Sierra Leonean" },
  { code: "sg", name: "Singaporean" },
  { code: "sk", name: "Slovak" },
  { code: "si", name: "Slovenian" },
  { code: "sb", name: "Solomon Islander" },
  { code: "so", name: "Somali" },
  { code: "za", name: "South African" },
  { code: "kr", name: "South Korean" },
  { code: "ss", name: "South Sudanese" },
  { code: "es", name: "Spanish" },
  { code: "lk", name: "Sri Lankan" },
  { code: "sd", name: "Sudanese" },
  { code: "sr", name: "Surinamese" },
  { code: "sz", name: "Swazi" },
  { code: "se", name: "Swedish" },
  { code: "ch", name: "Swiss" },
  { code: "sy", name: "Syrian" },
  { code: "tj", name: "Tajik" },
  { code: "tz", name: "Tanzanian" },
  { code: "th", name: "Thai" },
  { code: "tl", name: "Timorese" },
  { code: "tg", name: "Togolese" },
  { code: "to", name: "Tongan" },
  { code: "tt", name: "Trinidadian or Tobagonian" },
  { code: "tn", name: "Tunisian" },
  { code: "tr", name: "Turkish" },
  { code: "tm", name: "Turkmen" },
  { code: "tv", name: "Tuvaluan" },
  { code: "ug", name: "Ugandan" },
  { code: "ua", name: "Ukrainian" },
  { code: "ae", name: "Emirati" },
  { code: "gb", name: "British" },
  { code: "us", name: "American" },
  { code: "uy", name: "Uruguayan" },
  { code: "uz", name: "Uzbekistani" },
  { code: "vu", name: "Vanuatuan" },
  { code: "va", name: "Vatican" },
  { code: "ve", name: "Venezuelan" },
  { code: "vn", name: "Vietnamese" },
  { code: "ye", name: "Yemeni" },
  { code: "zm", name: "Zambian" },
  { code: "zw", name: "Zimbabwean" },
];
